name: Test & Deploy

on:
  pull_request:
    branches: [staging, main]
  push:
    branches: [staging, main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Chromium only
        run: npx playwright install chromium

      # Debug: show repo info for clarity
      - name: Debug PR origin
        run: |
          echo "PR repo: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Base repo: ${{ github.repository }}"

      # Fetch locations — only for trusted branches & same-repo PRs
      - name: Fetch locations JSON
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          echo "Running fetch-locations with MONGODB_URI..."
          npm run fetch:locations

      # Skip fetch for fork PRs, log clearly
      - name: Skip fetch for fork PRs
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}
        run: |
          echo "⏭️  Skipping fetch-locations: fork PRs cannot access secrets."

      # Run unit and integration tests (always)
      - name: Run unit and integration tests
        run: |
          npm run test:unit
          npm run test:integration

      # Skip E2E tests for fork PRs
      - name: Run E2E tests (trusted branches only)
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
        run: |
          echo "Running E2E tests"
          npm run test:e2e

      # Build & test: trusted branches / same-repo PRs
      - name: Build & test for trusted branches
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          echo "Running build with DB fetch..."
          npm run build

      # Build & test: fork PRs, skip prebuild by env flag
      - name: Build & test (skip tests) for fork PR
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}
        env:
          SKIP_FETCH: "true"
        run: |
          echo "Skipping tests for fork PR"
          npm run build

      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
